### ISSUE TITLE
2タブで開いたときユーザーデータが片方しか反映されない

### ISSUE THREAD

**Issue by simiraaaa** [phi-jp/runstant-lite#4]
起動時にlocalStorageからデータを取ってきているので、タブを2つ以上開いて同時に編集したとき最後に保存した方のデータになります。
今回実装されたプロジェクトの保存では、タブAとBを同時に開いたとき

Aを編集して保存
Bを編集して保存

を行ったときrunstantを開いた時点にBが追加された状態になります。
Aは消えます。

**Comment by simiraaaa** [comment]
対策はuser.dataにアクセスするとき毎回user.loadするとかでしょうか
速度が気になりますが
```
//user
//data アクセサ
{
  get(){
    //loadと同じことをして dataを返す
  }
}

```

**Comment by phi-jp** [comment]
@simiraaaa san
結局それでも同時編集はデータの不整合は起きてしまいます.
なので, http://lite.runstant.com でユーザー情報を編集するのではなく
http://lite.runstant.com/user で編集するよう集約していくつもりです.

要は, 右下のボタンを押すとユーザー編集画面にもう飛ばしちゃうってことです♪

**Comment by simiraaaa** [comment]
なんとなくニュアンスが伝わってないように思うので、もうちょっと説明すると
今回はプロジェクト保存機能を追加したのでプロジェクトが保存されるようになったんですが
localStorageのデータを読み込むのが起動の初回(ページを開いた時)だけなので、問題が発生しやすいということです。

タブをいくつか同時に開いたとします。

この時localStorage上のプロジェクトはAのみだとします。

タブ1でBを作り保存すると
プロジェクトAが存在する状態にBを追加して
A、Bというプロジェクトが一覧に並ぶようになります。

次に同時に開いていた別のタブ2でCを作り保存します。
そうするとタブ1と同じようにプロジェクトAとCがlocalStorageに上書き保存されます。
一覧にはACが表示され、さっき保存したBがなくなります。
希望としてはこのタイミングでABCが存在することです。
localStorageは別のタブで編集されても反映されるので、データにアクセスするとき毎回localStorageからデータを読み込めばこういう問題はほとんど発生しなくなります。

**Comment by phi-jp** [comment]
@simiraaaa 
あー, なるほど!
確かに, 今回プロジェクト履歴を保存するようになったのでこの問題は頻発しますね.

随時ロードするよう修正します!

**Comment by phi-jp** [comment]
@simiraaaa san

こちらで随時ロードして保存するよう対応しました.
https://github.com/phi-jp/runstant-lite/pull/5

お手すきの際にレビューしてもらえると嬉しいです♪

あと, 地味な変更としてユーザーデータとログデータを分離しました.
今後の拡張性を見越しての修正です.
